<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="816" height="1056" style="
    /* transform: scale(0.5); */
">
    <!--Generated by Aspose.Words for .NET 18.5-->
    <defs>
        <image id="image18" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAYAAACprHcmAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAjSURBVChTY9j/8Pv/hsPviMIMIIKx/R5ReFQxMh4Uiu/9BwDvkjLauCmybAAAAABJRU5ErkJggg==" width="11" height="11"></image>
        <image id="image16" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAQCAYAAAAmlE46AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAFYSURBVDhPbZIrTwNREIVbWYlEViKRSCQ/AVmJROJwFYhNEJBUlFQQggJBAoKkAtGkok0QEAR9UNryaFighQXaMs03m9nsoyc5u3fvnXPmcTeVzjckzqVCR1YPe7JS6ibOjBHh5uVAXG8qceQrrmR2mkkhm+W2p0EIj25Gsn3lysH1UPqjie7fDv5kwWlFhQQBxJRJZsRb5Tf9Zg0wCoS4AJyzew/SfB/rt1P90DcVICYjWC4++sK1475u4EYmAyYGzqyq3NmLL9y4eNUNytqvfUr96VcnSt+8z++/tQUEAAMVMnJwcvcl66fPugbhjEzVSidGhTjTnzf+13vDAFS6P8EbE3olZnG37Qt5WBkY0DMGlMSawVA+IDPxgRDayAGB9GVZAevwTxAI2TTnOKjESkwIIb3Yn2Kw3sNxMCKEBBFs4LriMTAhhHYtXMG8czhXCBGHhxFlQ2aaI64+LCHcUQAAAABJRU5ErkJggg==" width="14" height="16"></image>
        <image id="image14" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEESURBVDhPY2Bsv/efVGy58Ol/kjQmbnn1//6H32BMlMbAtS/+n3/x8z8MbL/7Db9Gx6XP/h9/+gOs+PmXP2AMAv2nPmLXCPLD/offwYpAAKR5+bUvUN7//4V73qBqNJz35P/6m1+h0hAA0lC5/x2UBwGeK59DNCpOe/R//qXPUGEEaD/+HqwIHUhOevifAeQPdPD99z9wCGrOevz//fe/UFEIAMmBLAPbCHIiyMOgYAYpBBkm2P8AzEcHoNCFa0TGIA0gGjkwkAFIHCSPNVRB8QZyBcjm6ec+oTgX5G+QGqwaYQEFCnaYGMgwkDjIMBAfp0ZQPGKTg2GsGkHOhPkVO773HwB2TUdgTJT4iwAAAABJRU5ErkJggg==" width="14" height="14"></image>
        <image id="image15" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAE8SURBVDhPfZIhTAJhFMfPSDQajUaikWg0Go1Goo1GMLAZdDPoDM4ZnAQ3DGwEApsBN4POIIiKojJPRT2U6XO/d7xPjh287e12997v3f/9v8+byNZkVM5s3MjsdjO25k2vXUum7Gsul54lsVJ3xYX8g5QagQS9X9k67chk7uofXDx8lMFIbt5GQOoMZ2j9pacqFJzbu+8jYczvtxxIE0rO29+SLrYltXMnJ60vVeVRHIz16psDgQ4uPlQFTxRQXzp6EjWHiRZ+8ONAJtNkEivNrpq1e/YegtmKrxANTDXQkkZWQObUakN/pCAvOIeDw5DVcdSMQbo7R5Yn2Mu+jcvIBcAAgiOwb0iMuwQREDMKl58K4x7nxwoE+7OKKYqAlrnjV202aDjoiQVJ5PGHuKA+ErTESa4bQ8jwnGvyB2eZP6atrai4AAAAAElFTkSuQmCC" width="14" height="14"></image>
        @if(!empty($addedItem->model->image))
            <image id="image5" width="189" height="189"
                   xlink:href="{{asset('files/uploads/'.$addedItem->model->image)}}"/>
        @else
            <image id="image5" width="189" height="189"
                   xlink:href="{{asset('cv-templates/images/NoImage.avif')}}"/>
        @endif
        <clipPath id="clip1">
            <path d="M-1,-1 L426.950012207,-1 L426.950012207,93 L-1,93 Z" clip-rule="evenodd"></path>
        </clipPath>
        <clipPath id="clip10">
            <path d="M-1,-1 L26,-1 L26,54 L-1,54 Z" clip-rule="evenodd"></path>
        </clipPath>
        <clipPath id="clip11">
            <path d="M9,19 L582,19 L582,771 L9,771 Z" clip-rule="evenodd"></path>
        </clipPath>
        <clipPath id="clip12">
            <path d="M-1,-1 L321,-1 L321,488.494995117 L-1,488.494995117 Z" clip-rule="evenodd"></path>
        </clipPath>
        <clipPath id="clip13">
            <path d="M-0.5,-1 L185.5,-1 L185.5,488.494995117 L-0.5,488.494995117 Z" clip-rule="evenodd"></path>
        </clipPath>
        <clipPath id="clip2">
            <path d="M-1,-1 L97.050003052,-1 L97.050003052,93 L-1,93 Z" clip-rule="evenodd"></path>
        </clipPath>
        <clipPath id="clip4">
            <path d="M9,19 L582,19 L582,771 L9,771 Z" clip-rule="evenodd"></path>
        </clipPath>
        <clipPath id="clip5">
            <path d="M-1,-1 L26,-1 L26,54 L-1,54 Z" clip-rule="evenodd"></path>
        </clipPath>
        <clipPath id="clip6">
            <path d="M-1,-1 L11,-1 L11,54 L-1,54 Z" clip-rule="evenodd"></path>
        </clipPath>
        <clipPath id="clip7">
            <path d="M-1,-1 L260,-1 L260,54 L-1,54 Z" clip-rule="evenodd"></path>
        </clipPath>
        <clipPath id="clip8">
            <path d="M-1,-1 L73,-1 L73,54 L-1,54 Z" clip-rule="evenodd"></path>
        </clipPath>
        <clipPath id="clip9">
            <path d="M-1,-1 L182,-1 L182,54 L-1,54 Z" clip-rule="evenodd"></path>
        </clipPath>
    </defs>
    <g transform="scale(0.39)">
        <g>
            <g transform="matrix(1,0,0,1,20,45)">
                <g transform="matrix(1,0,0,1,25,0)" clip-path="url(#clip1)">
                    <text  style="font: bold 1.6rem sans-serif; transform: translate(0px, 36px);" id="cv_template_name">
                            @if(!empty($addedItem))
                                @if($lang=="en")
                                    {{$addedItem->model->first_name.' '.$addedItem->model->surename}}
                                @else
                                    {{$addedItem->model->first_name_ar.' '.$addedItem->model->surename_ar}}
                                @endif
                            @else {{__("Your Name")}}
                            @endif
                    </text>
                    <g transform="matrix(1,0,0,1,0,43.330001831)">
                        <text>
                            <tspan x="0" y="12.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">Accomplished Operations executive with a successful track record overseeing </tspan>
                            <tspan x="0" y="26.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">regional Marketing, IT, HR/training and property in company and franchise </tspan>
                            <tspan x="0" y="40.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">operations for a large chain of restaurants.</tspan>
                        </text>
                    </g>
                </g>
                <g transform="matrix(1,0,0,1,450.950012207,0)" clip-path="url(#clip2)">
                    <g transform="matrix(1,0,0,1,2.025000095,0)">
                        <use xlink:href="#image5" width="92" height="92" transform="matrix(0.547619045,0,0,0.547619045,0,0)"></use>
                    </g>
                </g>
            </g>
            <g transform="matrix(1,0,0,1,10,0)">
                <g transform="matrix(1,0,0,1,0,0)" clip-path="url(#clip4)">
                    <g transform="matrix(1,0,0,1,10,137)">
                        <text>
                            <tspan x="0" y="17.357000351" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="12" fill="#ffffff"></tspan>
                        </text>
                    </g>
                </g>
            </g>
            <g transform="matrix(1,0,0,1,20,157)">
                <g transform="matrix(1,0,0,1,0,0)" clip-path="url(#clip5)">
                    <text>
                        <tspan x="0" y="50.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#ffffff"></tspan>
                    </text>
                </g>
                <path class="sidebar_color" d="M25,0 L35,0 L35,53 L25,53 Z" fill="#0187de" style="@if(!empty($addedItem->model->template_color)) fill:{{$addedItem->model->template_color}}; @elseif(!empty(session('chosen_cv_color'))) fill:{{session('chosen_cv_color')}}; @else fill:#0187de; @endif" fill-rule="evenodd"></path>
                <g transform="matrix(1,0,0,1,25,0)" clip-path="url(#clip6)">
                    <text>
                        <tspan x="0" y="50.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#ffffff"></tspan>
                    </text>
                </g>
                <path class="sidebar_color" d="M35,0 L294,0 L294,53 L35,53 Z" fill="#0187de" fill-rule="evenodd" style="@if(!empty($addedItem->model->template_color)) fill:{{$addedItem->model->template_color}}; @elseif(!empty(session('chosen_cv_color'))) fill:{{session('chosen_cv_color')}}; @else fill:#0187de; @endif"></path>
                <g transform="matrix(1,0,0,1,35,0)" clip-path="url(#clip7)">
                    <g transform="matrix(1,0,0,1,18,0)">
                        <text>
                            <tspan x="0" y="21.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#ffffff">dom.webster@example.co.uk </tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,18,29)">
                        <text>
                            <tspan x="0" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#ffffff">07912 345 678 </tspan>
                        </text>
                    </g>
                </g>
                <path class="sidebar_color" d="M294,0 L366,0 L366,53 L294,53 Z" fill="#0187de" fill-rule="evenodd" style="@if(!empty($addedItem->model->template_color)) fill:{{$addedItem->model->template_color}}; @elseif(!empty(session('chosen_cv_color'))) fill:{{session('chosen_cv_color')}}; @else fill:#0187de; @endif"></path>
                <g transform="matrix(1,0,0,1,294,0)" clip-path="url(#clip8)">
                    <text>
                        <tspan x="0" y="50.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#ffffff"></tspan>
                    </text>
                </g>
                <path class="sidebar_color" d="M366,0 L547,0 L547,53 L366,53 Z" fill="#0187de" fill-rule="evenodd" style="@if(!empty($addedItem->model->template_color)) fill:{{$addedItem->model->template_color}}; @elseif(!empty(session('chosen_cv_color'))) fill:{{session('chosen_cv_color')}}; @else fill:#0187de; @endif"></path>
                <g transform="matrix(1,0,0,1,366,0)" clip-path="url(#clip9)">
                    <g transform="matrix(1,0,0,1,18,0)">
                        <text>
                            <tspan x="0" y="21.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#ffffff">46 Roman Rd, </tspan>
                            <tspan x="0" y="35.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#ffffff"> Leeds, LS2 3ZR </tspan>
                        </text>
                    </g>
                </g>
                <path class="sidebar_color" d="M547,0 L572,0 L572,53 L547,53 Z" fill="#0187de" fill-rule="evenodd" style="@if(!empty($addedItem->model->template_color)) fill:{{$addedItem->model->template_color}}; @elseif(!empty(session('chosen_cv_color'))) fill:{{session('chosen_cv_color')}}; @else fill:#0187de; @endif"></path>
                <g transform="matrix(1,0,0,1,547,0)" clip-path="url(#clip10)">
                    <text>
                        <tspan x="0" y="50.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#ffffff"></tspan>
                    </text>
                </g>
            </g>
            <g transform="matrix(1,0,0,1,10,0)">
                <g transform="matrix(1,0,0,1,0,0)" clip-path="url(#clip11)">
                    <g transform="matrix(1,0,0,1,10,210)">
                        <text>
                            <tspan x="0" y="22.357000351" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="12" fill="#ffffff"></tspan>
                        </text>
                    </g>
                </g>
            </g>
            <g transform="matrix(1,0,0,1,20,235)">
                <g transform="matrix(1,0,0,1,25,0)" clip-path="url(#clip12)">
                    <text>
                        <tspan x="0" y="14.081999779" font-family="Century Gothic" font-weight="bold" font-style="normal" font-size="14" fill="#000000">OBJECTIVE</tspan>
                    </text>
                    <g transform="matrix(1,0,0,1,0,17.165000916)">
                        <text>
                            <tspan x="0" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">To find a fulfilling position where I can apply my skills and </tspan>
                            <tspan x="0" y="25.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">knowledge.</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,0,45.165000916)">
                        <text>
                            <tspan x="0" y="39.082000732" font-family="Century Gothic" font-weight="bold" font-style="normal" font-size="14" fill="#000000">EXPERIENCE</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,0,87.330001831)">
                        <text>
                            <tspan x="0" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">September 2015 to February 2019</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,0,101.330001831)">
                        <text>
                            <tspan x="0" y="11.798000336" font-family="Century Gothic" font-weight="bold" font-style="normal" font-size="10" fill="#020303">Executive Vice President</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,0,115.330001831)">
                        <text>
                            <tspan x="0" y="11.798000336" font-family="Century Gothic" font-weight="bold" font-style="normal" font-size="10" fill="#020303">Pizza Hut UK &amp; Ireland </tspan>
                            <tspan x="106.994003296" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">, St Albans, Herts</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,10.399999619,129.330001831)">
                        <text>
                            <tspan x="-0.5" y="19.048000336" font-family="Times New Roman" font-weight="normal" font-style="normal" font-size="7.5" fill="#020303">●</tspan>
                            <tspan x="11.600000381" y="19.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">Led operations involved in running the brand including </tspan>
                            <tspan x="11.600000381" y="33.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">Marketing, IT, HR/training, development/construction, </tspan>
                            <tspan x="11.600000381" y="47.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">property and P&amp;L for 200 store locations.</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,10.399999619,179.330001831)">
                        <text>
                            <tspan x="-0.5" y="11.048000336" font-family="Times New Roman" font-weight="normal" font-style="normal" font-size="7.5" fill="#020303">●</tspan>
                            <tspan x="11.600000381" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">Oversaw operations for all regional company and </tspan>
                            <tspan x="11.600000381" y="25.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">franchise locations.</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,10.399999619,207.330001831)">
                        <text>
                            <tspan x="-0.5" y="11.048000336" font-family="Times New Roman" font-weight="normal" font-style="normal" font-size="7.5" fill="#020303">●</tspan>
                            <tspan x="11.600000381" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">Assessed profitability of existing company processes to </tspan>
                            <tspan x="11.600000381" y="25.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">determine optimum organisational structure for </tspan>
                            <tspan x="11.600000381" y="39.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">maximum revenue growth.</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,0,249.330001831)">
                        <text>
                            <tspan x="0" y="31.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">August 2007 to September 2015</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,0,283.329986572)">
                        <text>
                            <tspan x="0" y="11.798000336" font-family="Century Gothic" font-weight="bold" font-style="normal" font-size="10" fill="#020303">Senior Vice President</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,0,297.329986572)">
                        <text>
                            <tspan x="0" y="11.798000336" font-family="Century Gothic" font-weight="bold" font-style="normal" font-size="10" fill="#020303">Café Rouge</tspan>
                            <tspan x="57.603000641" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">, London</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,10.399999619,311.329986572)">
                        <text>
                            <tspan x="-0.5" y="19.048000336" font-family="Times New Roman" font-weight="normal" font-style="normal" font-size="7.5" fill="#020303">●</tspan>
                            <tspan x="11.600000381" y="19.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">Directed departmental alignment on strategies to </tspan>
                            <tspan x="11.600000381" y="33.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">create strong sales.</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,10.399999619,347.329986572)">
                        <text>
                            <tspan x="-0.5" y="11.048000336" font-family="Times New Roman" font-weight="normal" font-style="normal" font-size="7.5" fill="#020303">●</tspan>
                            <tspan x="11.600000381" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">Cultivated strong franchise owner relationships to </tspan>
                            <tspan x="11.600000381" y="25.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">achieve high operating standards.</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,10.399999619,375.329986572)">
                        <text>
                            <tspan x="-0.5" y="11.048000336" font-family="Times New Roman" font-weight="normal" font-style="normal" font-size="7.5" fill="#020303">●</tspan>
                            <tspan x="11.600000381" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">Implemented process improvements to increase </tspan>
                            <tspan x="11.600000381" y="25.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">customer loyalty and satisfaction.</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,0,403.329986572)">
                        <text>
                            <tspan x="0" y="39.082000732" font-family="Century Gothic" font-weight="bold" font-style="normal" font-size="14" fill="#000000">QUALIFICATIONS</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,0,445.494995117)">
                        <text>
                            <tspan x="0" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">CGMA (Chartered Global Management Accountant) </tspan>
                            <tspan x="0" y="25.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">conferred by the Chartered Institute of Management </tspan>
                            <tspan x="0" y="39.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">Accountants (CIMA), 2010</tspan>
                        </text>
                    </g>
                </g>
                <g transform="matrix(1,0,0,1,345,0)" clip-path="url(#clip13)">
                    <g transform="matrix(1,0,0,1,20.5,0)">
                        <text>
                            <tspan x="0" y="14.081999779" font-family="Century Gothic" font-weight="bold" font-style="normal" font-size="14" fill="#000000">SKILLS</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,30.899999619,17.165000916)">
                        <text>
                            <tspan x="-0.5" y="11.048000336" font-family="Times New Roman" font-weight="normal" font-style="normal" font-size="7.5" fill="#020303">●</tspan>
                            <tspan x="11.600000381" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">Executive team leadership</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,30.899999619,31.165000916)">
                        <text>
                            <tspan x="-0.5" y="11.048000336" font-family="Times New Roman" font-weight="normal" font-style="normal" font-size="7.5" fill="#020303">●</tspan>
                            <tspan x="11.600000381" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">Multimillion pound P&amp;L </tspan>
                            <tspan x="11.600000381" y="25.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">management expertise for </tspan>
                            <tspan x="11.600000381" y="39.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">South East region</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,30.899999619,73.165000916)">
                        <text>
                            <tspan x="-0.5" y="11.048000336" font-family="Times New Roman" font-weight="normal" font-style="normal" font-size="7.5" fill="#020303">●</tspan>
                            <tspan x="11.600000381" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">Client/Vendor relations</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,30.899999619,87.165000916)">
                        <text>
                            <tspan x="-0.5" y="11.048000336" font-family="Times New Roman" font-weight="normal" font-style="normal" font-size="7.5" fill="#020303">●</tspan>
                            <tspan x="11.600000381" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">Marketing/product line </tspan>
                            <tspan x="11.600000381" y="25.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">development</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,30.899999619,115.165000916)">
                        <text>
                            <tspan x="-0.5" y="11.048000336" font-family="Times New Roman" font-weight="normal" font-style="normal" font-size="7.5" fill="#020303">●</tspan>
                            <tspan x="11.600000381" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">Staff/training policy </tspan>
                            <tspan x="11.600000381" y="25.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">development</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,30.899999619,143.164993286)">
                        <text>
                            <tspan x="-0.5" y="11.048000336" font-family="Times New Roman" font-weight="normal" font-style="normal" font-size="7.5" fill="#020303">●</tspan>
                            <tspan x="11.600000381" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">Process improvement</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,20.5,157.164993286)">
                        <text>
                            <tspan x="0" y="39.082000732" font-family="Century Gothic" font-weight="bold" font-style="normal" font-size="14" fill="#000000">EDUCATION</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,20.5,199.330001831)">
                        <text>
                            <tspan x="0" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">2006</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,20.5,213.330001831)">
                        <text>
                            <tspan x="0" y="11.798000336" font-family="Century Gothic" font-weight="bold" font-style="normal" font-size="10" fill="#020303">BA (Hons)</tspan>
                            <tspan x="47.196998596" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303"></tspan>
                            <tspan x="49.965999603" y="11.798000336" font-family="Century Gothic" font-weight="bold" font-style="normal" font-size="10" fill="#020303">Business Management</tspan>
                        </text>
                    </g>
                    <g transform="matrix(1,0,0,1,20.5,227.330001831)">
                        <text>
                            <tspan x="0" y="11.798000336" font-family="Century Gothic" font-weight="bold" font-style="normal" font-size="10" fill="#020303">University Of Westminster </tspan>
                            <tspan x="122.778999329" y="11.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">, </tspan>
                            <tspan x="0" y="25.798000336" font-family="Century Gothic" font-weight="normal" font-style="normal" font-size="10" fill="#020303">Greater London </tspan>
                        </text>
                    </g>
                </g>
                <path class="sidebar_color" d="M345,0 L345,487.494995117 " stroke-width="1" stroke-miterlimit="10" stroke="#0187de" fill="none" fill-rule="evenodd" style="@if(!empty($addedItem->model->template_color)) fill:{{$addedItem->model->template_color}}; @elseif(!empty(session('chosen_cv_color'))) fill:{{session('chosen_cv_color')}}; @else fill:#0187de; @endif"></path>
            </g>
            <g transform="matrix(1,0,0,1,10,0)">
                <path class="sidebar_color" d="M0,20 L0,770 " stroke-width="20" stroke-miterlimit="10" stroke="#0187de" fill="none" fill-rule="evenodd" style="@if(!empty($addedItem->model->template_color)) stroke:{{$addedItem->model->template_color}}; @elseif(!empty(session('chosen_cv_color'))) fill:{{session('chosen_cv_color')}}; @else fill:#0187de; @endif"></path>
                <path class="sidebar_color" d="M591,20 L591,770 " stroke-width="20" stroke-miterlimit="10" stroke="#0187de" fill="none" fill-rule="evenodd" style="@if(!empty($addedItem->model->template_color)) stroke:{{$addedItem->model->template_color}}; @elseif(!empty(session('chosen_cv_color'))) fill:{{session('chosen_cv_color')}}; @else fill:#0187de; @endif"></path>
                <path class="sidebar_color" d="M-10,10 L601,10 " stroke-width="20" stroke-miterlimit="10" stroke="#0187de" fill="none" fill-rule="evenodd" style="@if(!empty($addedItem->model->template_color)) stroke:{{$addedItem->model->template_color}}; @elseif(!empty(session('chosen_cv_color'))) fill:{{session('chosen_cv_color')}}; @else fill:#0187de; @endif"></path>
                <path class="sidebar_color" d="M-10,780 L601,780 " stroke-width="20" stroke-miterlimit="10" stroke="#0187de" fill="none" fill-rule="evenodd" style="@if(!empty($addedItem->model->template_color)) stroke:{{$addedItem->model->template_color}}; @elseif(!empty(session('chosen_cv_color'))) fill:{{session('chosen_cv_color')}}; @else fill:#0187de; @endif"></path>
            </g>
            <g transform="matrix(1,0,0,1,0,790)">
                <text>
                    <tspan x="0" y="0.077" font-family="Times New Roman" font-weight="normal" font-style="normal" font-size="1" fill="#ffffff">.</tspan>
                </text>
            </g>
            <g transform="matrix(1,0,0,1,55,170.5)">
                <use xlink:href="#image14" width="10.479331017" height="10.463819504" transform="matrix(0.748523653,0,0,0.747415662,0,0)"></use>
            </g>
            <g transform="matrix(1,0,0,1,55,189.5)">
                <use xlink:href="#image15" width="10.479331017" height="10.463819504" transform="matrix(0.748523653,0,0,0.747415662,0,0)"></use>
            </g>
            <g transform="matrix(1,0,0,1,386,170.5)">
                <use xlink:href="#image16" width="10.479331017" height="11.95861721" transform="matrix(0.748523653,0,0,0.747413576,0,0)"></use>
            </g>
            <g transform="matrix(1,0,0,1,360.5,235)">
                <use xlink:href="#image17" width="8.233758926" height="11.958632469" transform="matrix(0.748523533,0,0,0.747414529,0,0)"></use>
            </g>
            <g transform="matrix(1,0,0,1,360.5,422.165039062)">
                <use xlink:href="#image18" width="8.233758926" height="8.221554756" transform="matrix(0.748523533,0,0,0.747414052,0,0)"></use>
            </g>
        </g>
    </g>
</svg>
